apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: relationship-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: change-intelligence-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operations-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audit-service
  namespace: sentinel-app
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-worker
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: outbox-relay
  namespace: sentinel-workers
  annotations:
    azure.workload.identity/client-id: 49d48e76-b0ce-4a85-a92d-e9841ef4afc6
automountServiceAccountToken: true
